# -*- coding: utf-8 -*-
"""stockDataRetriever.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTNdheAKDKSYOuee6SKDZpVHNjoDjtm5
"""

import pandas as pd
import datetime
import matplotlib.pyplot as plt

def main(ticker):
    # replace 'stock_prices.csv' with your file name
    df = pd.read_csv('stock_prices.csv')
    df['Date'] = pd.to_datetime(df['Date'])

    # sort the dataframe by date
    df = df.sort_values('Date')

    # get the date in the dataset
    latest_date = df['Date'].max()

    # calc the date 52 weeks prior
    start_date = latest_date - datetime.timedelta(weeks=52)

    # filter data for the last 52 weeks
    df_52weeks = df[(df['Date'] >= start_date) & (df['Date'] <= latest_date)]

    # calculate 52-week low and high prices
    low_52week = df_52weeks['Price'].min()
    high_52week = df_52weeks['Price'].max()

    # calculate the average price over the entire dataset
    average_price = df['Price'].mean()

    # calculate daily price changes
    df['Price_Change'] = df['Price'].diff()
    df['Abs_Price_Change'] = df['Price_Change'].abs()

    # find the maximum absolute price change
    max_price_change = df['Abs_Price_Change'].max()
    biggest_move_dates = df[df['Abs_Price_Change'] == max_price_change]['Date']

    # calculate daily percentage changes
    df['Pct_Change'] = df['Price'].pct_change()
    df['Abs_Pct_Change'] = df['Pct_Change'].abs()

    # find the maximum absolute percentage change
    max_pct_change = df['Abs_Pct_Change'].max()
    biggest_pct_move_dates = df[df['Abs_Pct_Change'] == max_pct_change]['Date']

    # output results
    print("52-week low price: ${:.2f}".format(low_52week))
    print("52-week high price: ${:.2f}".format(high_52week))
    print("Average price over the year: ${:.2f}".format(average_price))
    print("\nDate of largest price move:")
    for date in biggest_move_dates:
        print(date.strftime('%Y-%m-%d'))
    print("Price change: ${:.2f}".format(max_price_change))
    print("Percentage price change: {:.2%}".format(max_pct_change))

    # make graph
    x = df['Date']
    y = df['Price']

    plt.plot(x, y)
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.title(ticker)

    plt.show()

if __name__ == '__main__':
    ticker = input("Enter stock ticker:")

    main(ticker)